theme: jekyll-theme-slate
title: Asteroides Cercanos a la Tierra (NEAs)
include: [2002_KL6_light_curve_pt1.max-600x600.png,771_Libera.PNG,asteroid-rotation-scrn10-700x150.max-1000x1000.png,asteroid-rotation-scrn11-855x150-2.max-1000x1000.png,asteroids-graphic-updatedlogo-01.width-500.png,screen_shot_2017-02-24_at_12.39.57-737x364.max-1000x1000.png]
source: index.html, estilos.css
